//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryDetail
    {
        public int id { get; set; }
        public Nullable<int> inventoryid { get; set; }
        public string locationid { get; set; }
        public Nullable<int> boxid { get; set; }
        public Nullable<int> boxqty { get; set; }
        public Nullable<int> itemqty { get; set; }
        public Nullable<int> capacity { get; set; }
        public Nullable<int> itemperbox { get; set; }
        public string lot { get; set; }
    
        public virtual Box Box { get; set; }
        public virtual Location Location { get; set; }
        public virtual Inventory Inventory { get; set; }
    }
}
