//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.InventoryDetails = new HashSet<InventoryDetail>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int id { get; set; }
        public string sku { get; set; }
        public string lot { get; set; }
        public string batch { get; set; }
        public Nullable<System.DateTime> expdate { get; set; }
        public Nullable<System.DateTime> inputdate { get; set; }
        public int companyid { get; set; }
        public int capacity { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Item Item { get; set; }
        public virtual ICollection<InventoryDetail> InventoryDetails { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
