//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Inventories = new HashSet<Inventory>();
        }
    
        public string sku { get; set; }
        public string name { get; set; }
        public Nullable<int> categoryid { get; set; }
        public Nullable<int> colorid { get; set; }
        public string description { get; set; }
        public string barcode { get; set; }
        public Nullable<int> companyid { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Color Color { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
    }
}
