//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.InventoryDetails = new HashSet<InventoryDetail>();
        }
    
        public string id { get; set; }
        public string description { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual ICollection<InventoryDetail> InventoryDetails { get; set; }
    }
}
