//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZInventory.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.CompanyOrders = new HashSet<CompanyOrder>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int statusid { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<System.DateTime> shippingdate { get; set; }
    
        public virtual ICollection<CompanyOrder> CompanyOrders { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
